### ISSUE TITLE
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type ...

### ISSUE THREAD

**Issue by neelsmith** [mechatroner/atom-rainbow-csv#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [rainbow-csv](https://github.com/mechatroner/atom-rainbow-csv) package 0.4.1

### Stack Trace

Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

```
At /Users/neelsmith/.atom/packages/rainbow-csv/index.js:71

TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at get_column_color (/packages/rainbow-csv/index.js:71:17)
    at display_position_info (/packages/rainbow-csv/index.js:100:56)
    at show_statusbar_tiles (/packages/rainbow-csv/index.js:204:9)
    at editor.onDidChangeCursorPosition.event (/packages/rainbow-csv/index.js:263:79)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1213350)
    at TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:33212)
    at Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:547364)
    at Selection.marker.onDidChange.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:532507)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1213350)
    at DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2854964)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2850466
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1213350)
    at Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:73563)
    at Marker.update (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:72617)
    at MarkerLayer.restoreFromSnapshot (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:79254)
    at TextBuffer.restoreFromMarkerSnapshot (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:503794)
    at TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:493399)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492416)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:33112)
    at TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:30265)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:96241)
```

### Commands

```
```

### Non-Core Packages

```
academic 0.34.1 
atom-beautify 0.33.4 
atom-criticmarkup 0.3.1 
atom-terminal 0.8.0 
atom-wrap-in-tag 0.6.0 
atom-xsltransform 1.0.0 
atomic-tei 0.0.1 
browser-plus 0.0.98 
busy-signal 2.0.1 
editor-settings 1.1.3 
elm 0.1.0 
elm-format 3.2.0 
export-html 3.1.0 
foldingtext-markdown 1.3.2 
Hydrogen 2.13.1 
hyperclick 0.1.5 
ide-haskell 2.4.1 
intentions 1.1.5 
language-elm 1.5.0 
language-groovy 0.7.0 
language-markdown 0.37.0 
language-pfm 0.82.0 
language-scala 1.1.10 
language-textile 0.2.0 
language-todotxt 1.1.5 
lilycompile 0.9.2 
linter 2.3.1 
linter-autocomplete-jing 0.8.4 
linter-coffeelint 2.0.20 
linter-javac 1.10.0 
linter-markdown 5.2.10 
linter-ui-default 1.8.0 
markdown-document 0.2.1 
markdown-folder 0.5.0 
markdown-mindmap 0.6.2 
markdown-pdf 2.2.0 
markdown-preview-enhanced 0.17.0 
markdown-preview-plus 3.11.5 
markdown-table-formatter 2.9.2 
markdown-themeable-pdf 1.2.1 
markdown-toc 0.4.2 
markdown-writer 2.11.9 
marked 0.1.10 
minimap-git-diff 4.3.1 
minimap-split-diff 0.3.7 
one-o-eight-syntax 0.38.0 
pandoc-convert 1.1.1 
pdf-view 0.72.0 
pen-paper-coffee-syntax 0.17.0 
pretty-json 2.1.2 
rainbow-csv 0.4.1 
script 3.25.0 
split-diff 1.6.1 
tablr 1.8.3 
tabular 0.1.0 
teletype 0.13.4 
textile-preview 0.1.2 
todo 0.6.0 
wordcount 3.1.0 
xml-formatter 0.13.0 
Zen 0.18.0 
zotero-citations undefined 
```

**Comment by mechatroner** [comment]
Thanks! I just published version 0.4.3 which should fix the problem. Please let me know if you still see this or some other bugs.

**Comment by neelsmith** [comment]
Thanks for the fast response!
